name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: dtb_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Récupérer le dépôt GitHub
        uses: actions/checkout@v4

      - name: Configurer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Attendre que MySQL soit prêt
        run: |
          until mysql -h localhost -P 3306 -uroot -proot -e "SELECT 1"; do
            echo "En attente de MySQL..."
            sleep 5
          done

      - name: Installer les dépendances de Node
        run: |
          cd code/server
          npm ci

      - name: Compiler TypeScript en JavaScript
        run: |
          cd code/server
          rm -rf dist
          npm run compile

      - name: Installer la base de données dans le serveur MySQL
        run: |
          cd code/server/mysql
          mysql -h localhost -P 3306 -uroot -proot < my_dtb.test.sql

      - name: Exécuter les tests
        run: |
          cd code/server
          npm run test
          npm run test:coverage
