# nom du workflow
name: cours_dtb CI/CD

# déclenchement du workflow
on: workflow_dispatch

# tâches
jobs:
  # nom de la tâche
  CI:
    # type d'environnement
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt GitHub
        # exécuter une commande prédéfinie : checkout
        uses: actions/checkout@v4

      - name: Installer les dépendances de Node
        # exécuter une commande personnelle : run
        run: |
          cd code/server
          npm ci

      - name: Compiler TypeScript en JavaScript
        run: |
          cd code/server
          rm -rf dist
          npm run compile

      - name: Installer la base de données dans le serveur MySQL
        run: |
          sudo service mysql start
          cd code/server/mysql
          mysql -uroot -proot -e 'SOURCE my_dtb.test.sql;'
          mysql -uroot -proot -e 'SHOW DATABASES;'
          mysql -uroot -proot -e 'USE dtb_test; SHOW TABLES;'

      - name: Exécuter les tests
        run: |
          cd code/server
          npm run test
          npm run test:coverage
